/*Ejemplo de movimiento*/

#include <stdio.h>
#include <conio.h>
#include <dos.h>
void main()
{
	int col,i, fil;
   for(col=5, fil=3;col<79;col++)
   {
   	gotoxy(col,fil);
      printf("<(=.=)>");
      gotoxy(col+7,fil-2);
      printf("zZzZz...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(0.=)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("\\(*0*)/");
      gotoxy(col+7, fil-2);
      printf("ooohhuaa!");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(+_+)>");
      gotoxy(col+7,fil-2);
      printf("niah...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("(\\o_o)\\");
      gotoxy(col+7,fil-2);
      printf("un..");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("/(o_o/)");
      gotoxy(col+7,fil-2);
      printf("dos..");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("\\(o_o\\)");
      gotoxy(col+7,fil-2);
      printf("un..");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("(/o_o)/");
      gotoxy(col+7,fil-2);
      printf("dos..");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("\\(^_^)/");
      gotoxy(col+7,fil-2);
      printf("wop");
      sleep(2);
      clrscr();
      gotoxy(col++,fil);
      printf("\\(^_^)/");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      gotoxy(col++,fil);
      printf("<(o_o^)>");
      gotoxy(col+7,fil-2);
      printf("...");
      for(i=0;i<888888888;i++);
      clrscr();
      for(col;col<60;col++)
      {
     	gotoxy(col,fil);
      printf("<(=.=)>");
      gotoxy(col+7,fil-2);
      printf("zZzZz...");
      for(i=0;i<888888888;i++);
      clrscr();
      }


   }
}
